### PR TITLE
feat(authentication): support sign-in with redirect on Web

### LINKED ISSUE #224: feat: support for `loginWithRedirect()`
**Is your feature request related to a problem? Please describe:**

Requesting support for `loginWithRedirect()` instead of PopUp, for web environments where we know pop-ups won't work and should not be attempted. Like electron, or other single-page platforms.

**Describe the solution you'd like:**

The CapacitorFirebase login/connect/etc APIs should support `opts: { mode?: 'popup' | 'redirect' }` as an option. PopUp can still be default, but ideally this would be configurable in web environments.

**Describe alternatives you've considered:**

Manually calling the Firebase JS API 

**Additional context:**

Firebase docs for loginWithRedirect:
https://firebase.google.com/docs/auth/web/google-signin#:~:text=To%20sign%20in%20by%20redirecting%20to%20the%20sign%2Din%20page%2C%20call%20signInWithRedirect%3A

Note, we will need an additional function or event listener to check for/receive the redirect OAuth token/results:

https://firebase.google.com/docs/auth/web/google-signin#:~:text=Then%2C%20you%20can%20also%20retrieve%20the%20Google%20provider%27s%20OAuth%20token%20by%20calling%20getRedirectResult%20when%20your%20page%20loads

### PR DESCRIPTION
**Pull request by robingenz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).

Close #224

### CODE REVIEW

**Comment by robingenz** [comment]
@lincolnthree You can give it a try if you want:

```
npm i @capacitor-firebase/authentication@1.2.0-dev.57e621c.1667594791
```

Would be glad if you give feedback.

**Comment by lincolnthree** [comment]
Thanks @robingenz, I will try this!

**Comment by alexookah** [comment]
Is this also supported for phoneLogin?

**Comment by robingenz** [comment]
@lincolnthree Have you already had the chance to test it?

**Comment by lincolnthree** [comment]
@robingenz Apologies. I have had a crazy few weeks. I haven't had a chance to test this yet. Is there a nightly build I can try?

**Comment by robingenz** [comment]
I don't know what I did there, half of the code is missing. 😆
Sorry for that, i will fix it and test it.

**Comment by robingenz** [comment]
@lincolnthree I fixed and tested it and published a new version:
```
npm i @capacitor-firebase/authentication@1.2.0-dev.e7b5a2a.1668711492
```

The `authStateChange` listener is invoked after the redirect.

**Comment by lincolnthree** [comment]
@robingenz Awesome! I will try this today or tomorrow. Sorry for the wait. Crazy week.

**Comment by lincolnthree** [comment]
One thing I'm curious about. How are error codes reported with this? It looks like it would just be an unhandled exception, or possibly be swallowed entirely, right?

Also, perhaps users should have some control over when the redirect result is checked, so it doesn't always get called if unnecessary? Maybe `FirebaseAuthentication.checkRedirectResult()` should be a more manual method call (but would still just trigger the auth event)?

Just thinking out loud.

https://firebase.google.com/docs/reference/js/v8/firebase.auth.Auth#getredirectresult

**Comment by robingenz** [comment]
You are right. I improve that.

**Comment by robingenz** [comment]
@lincolnthree I have implemented and tested your suggestions and am much happier with the new solution. Thanks for your ideas! Here's a dev version in case you want to try it out as well: 
```
npm i @capacitor-firebase/authentication@1.2.0-dev.21cdd25.1669210347
```
I merge this PR in a timely manner.

**Pull request merged**
