### PR TITLE
feat(authentication): support `serverAuthCode` for Google Sign-in

### PR DESCRIPTION
**Pull request by robingenz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).

Related to https://github.com/capawesome-team/capacitor-firebase/discussions/433

### CODE REVIEW

**Comment by robingenz** [comment]
@RaduMirceaAndrei Here is a new dev version for testing with both features:

```
npm i @capacitor-firebase/authentication@5.1.0-dev.2e8ccf1.1695811597
```

Please let me know if everything works as expected.

**Comment by RaduMirceaAndrei** [comment]
@robingenz I've tested and unfortunately, no refresh_token. I took a second look at the Firebase [documentation](https://firebase.google.com/docs/auth/extend-with-blocking-functions?gen=2nd#google) specifically for refresh tokens and also at the URL that's generated inside the popup for the web (login via web does produce a refresh token). It seems i made in incorrect assumption.

The url looks like this:

https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?response_type=code&<client_id>.apps.googleusercontent.com&redirect_uri=https%3A%2F%2F<app_name>%2F__%2Fauth%2Fhandler&state=AMbdmDkt8dhRLLzj9mN1ooPoSQWdCAXmaF_haJyVC4rt5jAkGwQlKwn5v2rCfoBsi14Bu4KKSCwKlczafkSMW1s-MBR9A0p6ZvMlD81tR1Q3tT-Woi47zZ9IdqEUxYsXQs5KONMeVx7Sw66k4wp0MHYclJISjGi3DYURSdTKXmFZbfL8domnWYRRYFrjQxQTF7U_cuwAoHPLdee2w8NrCMYGN602moEFMrZvMpqolBv0P9qbP0OzJHBoo2XZ2J73rYVznPg6pJL118WlXDbHe-al4O4KY8_HpeES3g17dOho2dMKYE4QJnqX3LBGvZ1kIxWEh6UWc2E&scope=openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.events%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.readonly&**prompt=consent&access_type=offline**&context_uri=http%3A%2F%2Flocalhost%3A8100&service=lso&o2v=1&theme=glif&flowName=GeneralOAuthFlow

Of note are actually two parameters, 
```prompt=consent``` and ```access_type=offline```.

The Firebase [documentation](https://firebase.google.com/docs/auth/extend-with-blocking-functions?gen=2nd#google) says that a refresh token will be returned if both parameters are sent. 
```When a user signs in with Google, the following credentials will be passed:

- ID token
- Access token
- Refresh token: Only provided if the following custom parameters are requested:

1. access_type=offline
2. prompt=consent, if the user previously consented and no new scope was requested
```


They also give an example using the JS-SDK 


```import { getAuth, signInWithPopup, GoogleAuthProvider } from 'firebase/auth';

const auth = getAuth();
const provider = new GoogleAuthProvider();
provider.setCustomParameters({
  'access_type': 'offline',
  'prompt': 'consent'
});
signInWithPopup(auth, provider);
```

I had assumed that the only missing parameter was "access_type" and that "prompt" would be implicit on scope request, since it prompts the user. Given their example and the way it is worded, It appears it needs to be explicitly sent.

That's about all i could find. There may be specific, platform requirements in order to get a refresh token, but i could not find the documentation for that. I apologize for the confusion.

**Comment by robingenz** [comment]
@RaduMirceaAndrei But it should work on Android. You're only referring to iOS, right?

**Comment by RaduMirceaAndrei** [comment]
@robingenz I've tested on all 3 platforms (web included). There are no more discrepancies between the sign in flow on iOS and Android. Both platforms will show the scopes permissions screen and the resulting access token contains the granted scopes. A refresh token will not be generated for iOS or for Android, and it will not be passed to Firebase. That only happens on the web. My best guess is, because the endpoint auth endpoint needs to be called with both ```prompt=consent``` and ```access_type=offline``` parameters (but this guess is based on the firebase documentation and the url in the web popup).

**Comment by RaduMirceaAndrei** [comment]
@robingenz Hi. Apologies for the late reply, i've been out of comision for a couple of days.
I indeed receive a ```serverAuthCode``` (of the form ```4/0..```), however, that's a temporary code and can only be exchanged for an ```access_token```from what i understand. What i'm looking for is a ```refresh_token```. Refresh tokens are not temporary and can be used to obtain new access tokens and they only expire when you revoke them or when you revoke app connections from your google account (https://myaccount.google.com/connections).

Now, google will only send back a refresh token on the app's first authorization, or when an app requests new scopes (login with prompt and permission scopes screen) only if you're sending that request with the two parameters ```access_type=offline``` and ```prompt=consent```. That part of the firebase authentication would be the native layer login, so this:
```
FirebaseAuthentication.signInWithGoogle({
     scopes: ['https://www.googleapis.com/auth/calendar.events', 'https://www.googleapis.com/auth/calendar.readonly'],
     customParameters: [{key: 'access_type', value: 'offline'}, {key: 'prompt', value: 'consent'}]
});
```

Firebase however, will not send back to the user a refresh token, but, you can catch that token in a cloud function.
The thing is, when i go trough authentication flow on the web, i am able to grab the refresh token in said cloud function, in Firebase. The relevant part of the response object, from Google is looks like this
```
additionalUserInfo: {
        providerId: 'google.com',
        profile: {
            granted_scopes: 'https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile openid https://www.googleapis.com/auth/calendar.readonly',
        },
        isNewUser: true
    },
    credential: {
        claims: undefined,
        idToken: 'eyJhb...',
        accessToken: 'ya29.a0AfB...',
        refreshToken: '1//05wTtDxzYWhDWCgYIARAAGAUSNwF...',
        expirationTime: 'Sat, 30 Sep 2023 11:53:24 GMT',
        secret: '',
        providerId: 'google.com',
        signInMethod: 'google.com'
    }
```

A you can see, the refresh_token is of the form `1//05..`. 
I can also look at the url that the popup screen and for the step when you chose the account to sing in with it's:

```

https://accounts.google.com/o/oauth2/auth/oauthchooseaccount?response_type=code&client_id=<client_id>&redirect_uri=<redirect_uri>&state=AMbdmDkyhz68qF40JyQ-MurnZrYgPSSB9vMPXKiL_0uUNdvejKacBcPre6CAB12CH4oJyLP1emPdHwuTt6R6CBV-CedwgyVt-AuhsteawhAxntnor-tHa9CFrOht1Z8p3MQDIS1BXi1DHQHM5psjogfYFnYkgkkHwPskJz20F8vtCUpT19VqJkvG_xUHUkefD4jJvJKGKX2ajp6MMdgfBtilHD2Ya4UUyuQ_HV0YmG0710eAmhvsr7PVlHifyARZ9OdLtDhYL_RvhXSF136Epr5ZbCuZnYjILtVcH0SaK6UtLS6FbcQbm2tgR3JTYd_fUH1yK_K5-YQ&scope=openid%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email%20profile%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.events%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcalendar.readonly&access_type=offline&prompt=consent&context_uri=http%3A%2F%2Flocalhost%3A8100&service=lso&o2v=1&theme=glif&flowName=GeneralOAuthFlow
```
So the url contains the `access_type=offline&prompt=consent`.
Screenshot 2023-09-30 at 3 36 58 PM

    
On iOS and Android, i am getting the same thing in the response object in cloud, except that ```refreshToken: undefined```.  

Unfortunately, i could not see what URL the popup screen for the "chose account" part is of the authentication flow is, however, i'm guessing it's missing the two parameters. It's the only thing that would make sense based on the documentation and web behavior. Again, this is my assumption.

I understand this is getting into the unsupported "customParameters" part, however i figured that since for this particular use case the custom parameters are just calling the same endpoint with two added strings, perhaps it would be something achievable. Again, i don't understand much on the native side, but hopefully i've at least explained things in a way that makes sense.

**Pull request merged**
