### PR TITLE
feat(authentication): provide the auto-retrieved SMS verification code

### LINKED ISSUE #252: feat(authentication): provide the auto-retrieved SMS verification code
**Is your feature request related to a problem? Please describe:**

See https://github.com/capawesome-team/capacitor-firebase/discussions/251

**Describe the solution you'd like:**

Support https://firebase.google.com/docs/reference/kotlin/com/google/firebase/auth/PhoneAuthCredential#getSmsCode().

**There is also currently a bug which will then be noticed:**
The `onVerificationCompleted` callback may never be resolved during phone authentication, since the call is previously resolved via `onCodeSent`.
https://github.com/capawesome-team/capacitor-firebase/blob/fadf36b317207d54949828b0c6cf361de253f17e/packages/authentication/android/src/main/java/io/capawesome/capacitorjs/plugins/firebase/authentication/handlers/PhoneAuthProviderHandler.java#L69

**Describe alternatives you've considered:**

**Additional context:**

### PR DESCRIPTION
**Pull request by robingenz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).

Close #252

### CODE REVIEW

**Comment by robingenz** [comment]
```
npm i @capacitor-firebase/authentication@1.2.0-dev.048a0c5.1670093474
```

**Review by alexookah — APPROVED** [review]
Looks good :)

**Comment by alexookah** [comment]
@robingenz 
I just tested it and login by entering code works good. But the `phoneVerificationCompleted` is not firing.

**Comment by robingenz** [comment]
`phoneVerificationCompleted` is only available on Android and fires not always but only when an SMS is auto-retrieved or the phone number has been instantly verified.

**Comment by alexookah** [comment]
How can I test the branch main?

**Comment by robingenz** [comment]
@alexookah I created a new dev build for you:
```
npm i @capacitor-firebase/authentication@1.2.0-dev.4c00b61.1670180888
```

**Comment by alexookah** [comment]
Can I also test this also with the messaging? because I am also using the messaging and it's not very easy

**Comment by robingenz** [comment]
@alexookah Yes, with this release ^^
```
npm i @capacitor-firebase/messaging@1.2.0-dev.4c00b61.1670180888
```

**Comment by alexookah** [comment]
Thanks for the dev build.
I did not succeed getting the trigger with the `phoneVerificationCompleted`. Just tried it in a real device and didn't work. Maybe we are missing something?

**Comment by alexookah** [comment]
I tested it from a apk that I downloaded from google play conolse as beta. 
Would it make a difference if it was a production app?

**Comment by carlossk** [comment]
Hi @robingenz, I have recently started to have a problem related to auto-retrieved SMS in android, does the plugin have any way to disable that mechanism?
Currently our users have experienced this error, it seems that the code is retrieved and burned by android automatically 
`{"code":"auth/code-expired","customData":{},"name":"FirebaseError"}`

**Comment by robingenz** [comment]
> Hi @robingenz, I have recently started to have a problem related to auto-retrieved SMS in android, does the plugin have any way to disable that mechanism?
> 
> Currently our users have experienced this error, it seems that the code is retrieved and burned by android automatically 
> 
> `{"code":"auth/code-expired","customData":{},"name":"FirebaseError"}`

No, you cannot disable this mechanism. See https://github.com/firebase/quickstart-android/issues/296

**Comment by efstathiosntonas** [comment]
@robingenz you can patch it to stop autoverify: https://github.com/firebase/quickstart-android/issues/296#issuecomment-1736910311

Being this for a year and had 0 issues so far.

**Comment by robingenz** [comment]
@efstathiosntonas Thanks for sharing! Would you be willing to create a PR which allows you to set the timeout?

**Comment by efstathiosntonas** [comment]
@robingenz I'd be happy to do so but unfortunatelly I do not use capacitor and I'm not familiar with the source code. 🤷‍♂️

**Comment by robingenz** [comment]
@efstathiosntonas All right! Thanks for the tip anyway. I will implement it.

**Pull request merged**
