### PR TITLE
feat(authentication): support `scopes` option for Google Sign-In on iOS

### LINKED ISSUE #437: feat: iOS Google Authentication scopes support
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Messaging
- [ ] Performance
- [ ] Remote Config

### Current problem

Hi,

On iOS "scopes" are not being passed to Google authentication and the scopes permissions screen is completely skipped in the authentication flow. It would be great if support could be added for iOS.

Thank you!

### Preferred solution

Ideally, the authentication flow would function like it does on Web and Android, with scopes being passed to Google and the scopes screen shown to the user for confirmation, if any non default (userinfo.email, userinfo.profile, openid) scopes are requested.

### Alternative options

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by robingenz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).

Close #437

### CODE REVIEW

**Comment by robingenz** [comment]
```
npm i @capacitor-firebase/authentication@5.1.0-dev.d1e8630.1695805346
```

**Comment by RaduMirceaAndrei** [comment]
Hi. Just need to change line 40 in GoogleAuthProvideHandler to ```GIDSignIn.sharedInstance.signIn(withPresenting: controller, hint: nil, additionalScopes: scopes) { (result, error) in```.

**Comment by nkalupahana** [comment]
@robingenz ^ the merged code is incorrect

**Comment by robingenz** [comment]
@nkalupahana Yes, I know (see https://github.com/capawesome-team/capacitor-firebase/issues/437#issuecomment-1737097487). I published a new dev version with a fix: https://github.com/capawesome-team/capacitor-firebase/pull/442#issuecomment-1737160112

**Pull request merged**
