### PR TITLE
feat(authentication): support `actionCodeSettings` in `sendEmailVerification(...)` and `sendPasswordResetEmail(...)`

### LINKED ISSUE #656: feat: passing state in email actions
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [X] Authentication
- [ ] Crashlytics
- [ ] Cloud Firestore
- [ ] Cloud Functions
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

`sendEmailVerification()` & `sendPasswordResetEmail()` do not support to pass the action code settings.
`sendSignInLinkToEmail()` already support these settings.

### Preferred solution

These settings provide the user the ability to go back to the app after the action is completed.

Firebase documentation:
- Web: https://firebase.google.com/docs/auth/web/passing-state-in-email-actions
- Android: https://firebase.google.com/docs/auth/android/passing-state-in-email-actions
- iOS: https://firebase.google.com/docs/auth/ios/passing-state-in-email-actions

### Alternative options

_No response_

### Additional context

_No response_

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

### PR DESCRIPTION
**Pull request by robingenz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [ ] A changeset has been created (`npm run changeset`).
- [ ] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

Close #656

### CODE REVIEW

**Comment by robingenz** [comment]
```
npm i @capacitor-firebase/authentication@6.0.0-dev.f54d9c3.1719494206
```

**Comment by mamillastre** [comment]
I focused my tests on providing only a url.

On web: all is fine.

On Android:
- The "handleCodeInApp" conf is mandadory but must be false by default
- When creating the "SendPasswordResetEmailOptions" object, the email is not initialized so we have an error.

On iOS: I do not complete the tests yet, I reached the free quota and I can't do more test today.
I had an error on iOS that I do not understand yet ("DYNAMIC_LINK_NOT_ACTIVATED: FDL domain is not configured", but the handleCodeInApp is false and must not use Firebase deep link)

**Comment by robingenz** [comment]
> The "handleCodeInApp" conf is mandadory but must be false by default

This should already be implemented. `setHandleCodeInApp(...)` is only called if the user actively sets it. According to firebase docs, the default value is already false.

> When creating the "SendPasswordResetEmailOptions" object, the email is not initialized so we have an error.

Sorry, fixed that.

> On iOS: I do not complete the tests yet, I reached the free quota and I can't do more test today.
I had an error on iOS that I do not understand yet ("DYNAMIC_LINK_NOT_ACTIVATED: FDL domain is not configured", but the handleCodeInApp is false and must not use Firebase deep link)

Feel free to set a debug point [here](https://github.com/capawesome-team/capacitor-firebase/blob/fdcd49e5561d505f3d3b31cf7a29c15bd9d80e90/packages/authentication/ios/Plugin/FirebaseAuthenticationHelper.swift#L30) to check if it's called or not. It should already be false by default. Have you tried actively setting it to `false`?

This is a new dev build:

```ts
npm i @capacitor-firebase/authentication@6.0.0-dev.5ac80c2.1719573986
```

**Comment by mamillastre** [comment]
> > The "handleCodeInApp" conf is mandadory but must be false by default
> 
> This should already be implemented. `setHandleCodeInApp(...)` is only called if the user actively sets it. According to firebase docs, the default value is already false.

Sorry, my feedback was not clear enough.
You do not provide a default value so it's throwing an exception and we get the error "No value for handleCodeInApp".
To keep the firebase default value, we need to use the "null" default value when getting the setting:
`Boolean handleCodeInApp = settings.getBoolean("handleCodeInApp", null);`

> > On iOS: I do not complete the tests yet, I reached the free quota and I can't do more test today.
> > I had an error on iOS that I do not understand yet ("DYNAMIC_LINK_NOT_ACTIVATED: FDL domain is not configured", but the handleCodeInApp is false and must not use Firebase deep link)
> 
> Feel free to set a debug point [here](https://github.com/capawesome-team/capacitor-firebase/blob/fdcd49e5561d505f3d3b31cf7a29c15bd9d80e90/packages/authentication/ios/Plugin/FirebaseAuthenticationHelper.swift#L30) to check if it's called or not. It should already be false by default. Have you tried actively setting it to `false`?

The options passed to Firebase seem valid. I think it's a missing configuration but I will continue the tests later.

**Comment by robingenz** [comment]
>  To keep the firebase default value, we need to use the "null" default value when getting the setting:

Done

New dev version:

```bash
npm i @capacitor-firebase/authentication@6.0.0-dev.456ae31.1719589152
```

**Comment by mamillastre** [comment]
I finally found the problem on iOS, the "handleCodeInApp" param seems to be inverted by FirebaseAuth. I do not understand why. It's not how the documentation describes it.
Is it a regression of FirebaseAuth ?

But otherwise, all the platforms seem ok now (on the plugin side).

**Comment by robingenz** [comment]
Thank you for testing! What do you mean by "inverted"? You pass true and the SDK sets false?

**Comment by mamillastre** [comment]
Yes, if we pass false (or let the default value as false), firebase want to open the app using a deep link.
If we pass true, a Firebase page handle the action.
This is not the behavior described in the Firebase documentation (https://firebase.google.com/docs/auth/ios/passing-state-in-email-actions#passing_statecontinue_url_in_email_actions).

**Comment by robingenz** [comment]
That is strange. Since this seems to be a problem with the Firebase SDK, I'm merging this PR. Feel free to open an issue in https://github.com/firebase/firebase-ios-sdk.

**Pull request merged**
