### PR TITLE
feat(emulator): add the emulator support on firestore, functions and storage packages

### LINKED ISSUE #603: feat: Emulator support for Firestore
### Plugin(s)

- [ ] Analytics
- [ ] App
- [ ] App Check
- [ ] Authentication
- [ ] Crashlytics
- [X] Cloud Firestore
- [ ] Cloud Messaging
- [ ] Cloud Storage
- [ ] Performance
- [ ] Remote Config

### Current problem

Unable to connect to locally running Firestore emulator

### Preferred solution

Would like to use the `connectFirestoreEmulator` method from `firebase/firestore` to connect to an emulator either at localhost or through a reverse proxy. Note that reverse proxy requires the `initializeFirestore(app, { host });` method because `connectFirestoreEmulator` requires a port.

### Alternative options

I did try to use the Firebase SDK methods to connect to the emulator but I can see the network requests still routing through the live Firestore url.

### Additional context

I started writing a PR for this but an issue, as mentioned above, is that the `connectFirestoreEmulator` does not allow for host-only, making reverse proxy unusable. In that case, using `initializeFirestore(app, { host });` instead works.

Here's the method for `web.ts` in `capacitor-firebase/firestore`, but I'm unsure whether `initializeFirestore` here is going to cause issues:

```
  export interface UseEmulatorOptions {
    host: string;
    port?: number;
  }
 
  // ... In the FirebaseFirestoreWeb definition

  public async useEmulator(options: UseEmulatorOptions): Promise<void> {
    const firestore = getFirestore();
    
    if (options.port) {
      connectFirestoreEmulator(firestore, options.host, options.port);
    } else {
      initializeFirestore(firestore.app, {
        host: options.host
      });
    }
  }
  ```
  
I have not looked at the native code to see what might need to be changed there.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

### PR DESCRIPTION
**Pull request by mamillastre**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).
- [x] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

Close #603

### CODE REVIEW

**Comment by robingenz** [comment]
Is this PR ready for review?

**Comment by mamillastre** [comment]
Not yet. I want to finalize some tests first.

**Comment by robingenz** [comment]
FYI: I plan to publish version 6.1.0 next week. If you want we can merge this PR before.

**Comment by mamillastre** [comment]
Thank you, I will try to find some times to test it well.
But it can wait for the next release.

**Comment by mamillastre** [comment]
@robingenz I finalized my tests.
It's ready for review.

**Review by robingenz — APPROVED** [review]
Thank you for your contribution!

**Pull request merged**
