### PR TITLE
Update README.md to follow what is in the code

### PR DESCRIPTION
**Pull request by riderx**
In the code the default version has changed:

https://github.com/capawesome-team/capacitor-firebase/blob/afb8548bce82678474de488e7656ad91155449a0/packages/crashlytics/android/build.gradle#L6

## Pull request checklist

Please check if your PR fulfills the following requirements:

- [X] The changes have been tested successfully.
- [X] A changeset has been created (`npm run changeset`).
- [X] I have read and followed the [pull request guidelines](https://capawesome.io/contributing/pull-requests/).

### CODE REVIEW

**Review by robingenz — APPROVED** [review]
Thank you!

**Comment by riderx** [comment]
@robingenz i just check in the code of my client and the old value is in place,
Do this version is released ?

**Comment by robingenz** [comment]
@riderx No, it's not yet released. This is the upcoming release for Capacitor 6.

**Comment by riderx** [comment]
ok thanks

**Pull request merged**
