### PR TITLE
feat(authentication): add Capacitor 5 support

### PR DESCRIPTION
**Pull request by ekoeryanto**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [ ] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).

ref: #351

### CODE REVIEW

**Comment by ekoeryanto** [comment]
edited from github web, sorry

**Comment by robingenz** [comment]
Hi @ekoeryanto, thank you for your contribution!
Please create a changeset using `npm run changeset`.

**Comment by robingenz** [comment]
I'm in the process of updating all Firebase plugins in one PR right now. I would therefore close your PR as the CI failed.
However, thank you so much for your contribution. I will do a pre-release this weekend.

**Comment by ekoeryanto** [comment]
> I'm in the process of updating all Firebase plugins in one PR right now
so I will wait for it and close this one.
thanks

**Comment by robingenz** [comment]
I just created the PR: #355

**Pull request closed without merging**
