### PR TITLE
fix(analytics): allow screen name to be set without screen class and vice-versa

### LINKED ISSUE #334: bug(analytics): Cannot set the current screen name without also overriding the screen class
**Plugin(s):**
`@capacitor-firebase/analytics": "^1.3.0"`

**Platform(s):**
iOS

**Current behavior:**
If `FirebaseAnalytics.setCurrentScreen` is called with a `screenName` but no `screenClassOverride`, the `screenName` is ignored and the event is logged in Firebase without the `firebase_screen` parameter.

**Expected behavior:**
It should be possible to set the screen name without needing to override the screen class. The `SetCurrentScreenOptions` interface implies that `screenClassOverride` is optional.

**Steps to reproduce:**
Set the current screen using:
```ts
FirebaseAnalytics.setCurrentScreen({
  screenName: 'Test'
})
```
and check for a `firebase_screen` parameter in the `screen_view` event logged in Firebase.

**Related code:**
In `FirebaseAnalytics.swift`, the `params` dictionary is only initialised if both `screenName` and `screenClass` are non-nil:

```swift
        if screenName != nil && screenClass != nil {
            params = [:]
        }
```

**Other information:**

**Capacitor doctor:**

```
💊   Capacitor Doctor  💊

Latest Dependencies:

  @capacitor/cli: 4.7.0
  @capacitor/core: 4.7.0
  @capacitor/android: 4.7.0
  @capacitor/ios: 4.7.0

Installed Dependencies:

  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1
  @capacitor/cli: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌
```

### PR DESCRIPTION
**Pull request by cconn**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).

Close #334

### CODE REVIEW

**Review by robingenz — APPROVED** [review]
Thank you for your contribution!

**Comment by robingenz** [comment]
Please generate a changeset: `npm run changeset`

**Review by robingenz — CHANGES_REQUESTED** [review]
Please generate a changeset: `npm run changeset`

**Review by robingenz — APPROVED** [review]

**Comment by cconn** [comment]
> Please generate a changeset: `npm run changeset`

Thanks for reviewing this so quickly! I've added the changeset.

**Comment by robingenz** [comment]
Great, thank you!

**Pull request merged**
