### PR TITLE
feat: add `@capacitor-firebase/storage` package

### LINKED ISSUE #63: feat: Cloud Storage for Firebase
Hi,

Any reason for not having `Cloud Storage for Firebase` on this plugin? Thanks!

`Doc:` https://firebase.google.com/docs/storage

### PR DESCRIPTION
**Pull request by robingenz**
## Pull request checklist

Please check if your PR fulfills the following requirements:

- [x] The changes have been tested successfully.
- [x] A changeset has been created (`npm run changeset`).

Close #63

### CODE REVIEW

**Comment by CatalystMonish** [comment]
Woah I was just looking for this, please please update this soon :)

**Comment by robingenz** [comment]
@CatalystMonish Yeah, I'm working on it ;)

**Comment by CatalystMonish** [comment]
> @CatalystMonish Yeah, I'm working on it ;)

Am I dumb or is there a way to getDownloadURL for a path, using the web SDK for Android and web?

**Comment by CatalystMonish** [comment]
Okay woah, I see the build happening, I might be the first outsider to use this plugin, I feel honoured, thanks @robingenz

**Comment by robingenz** [comment]
> Am I dumb or is there a way to getDownloadURL for a path, using the web SDK for Android and web?

Yes, you can basically use the Firebase JS SDK on Android as well.

**Comment by FrancescoIoppolo** [comment]
We look forward to it! Thank you, this is essential for me 😊

**Comment by robingenz** [comment]
@CatalystMonish @FrancescoIoppolo The first version is now available as dev version: 

```
npm i @capacitor-firebase/storage@5.1.0-dev.bf4bd39.1697375834
```

Here you can find the documentation: https://github.com/capawesome-team/capacitor-firebase/blob/feat/storage/packages/storage/README.md

**Comment by CatalystMonish** [comment]
> @CatalystMonish @FrancescoIoppolo The first version is now available as dev version:
> 
> ```
> npm i @capacitor-firebase/storage@5.1.0-dev.bf4bd39.1697375834
> ```
> 
> Here you can find the documentation: https://github.com/capawesome-team/capacitor-firebase/blob/feat/storage/packages/storage/README.md

Thankyou I will check it out 🙌

**Comment by FrancescoIoppolo** [comment]
> @CatalystMonish @FrancescoIoppolo The first version is now available as dev version:
> 
> ```
> npm i @capacitor-firebase/storage@5.1.0-dev.bf4bd39.1697375834
> ```
> 
> Here you can find the documentation: https://github.com/capawesome-team/capacitor-firebase/blob/feat/storage/packages/storage/README.md

I'll try right away! 🙌🙌

**Comment by robingenz** [comment]
Let me know if you encounter any issues. 🙌🏻

**Comment by FrancescoIoppolo** [comment]
I quickly implemented this code:
But it returns: Uncaught (in promise) **Error: blob must be provided.**

Do you have some advice?

`const uploadFile = async () => {
      return new Promise(async (resolve, reject) => {
        await FirebaseStorage.uploadFile(
          {
            path: 'images/mountains.png',
            uri: blob,
          },
          (event, error) => {
            if (error) {
              reject(error);
            } else if (event?.completed) {
              resolve();
            }
          }
        );
      });
    };
`

**Comment by FrancescoIoppolo** [comment]
It's working perfectly!! You're great
Thank you

**Comment by FrancescoIoppolo** [comment]
In Ios using the URI returned by Capacitor Camera I get this error:

**[error] - {"message":"File at URL: capacitor://localhost/_capacitor_file_/private/var/mobile/Containers/Data/Application/30DED4BA-4EB9-4F3A-AC39-BB7F7AA46053/tmp/photo-5. jpg is not reachable. Ensure file URL is not a directory, symbolic link, or invalid url.","errorMessage":"File at URL: capacitor://localhost/_capacitor_file_/private/var/mobile/Containers/Data/Application /30DED4BA-4EB9-4F3A-AC39-BB7F7AA46053/tmp/photo-5.jpg is not reachable. Ensure file URL is not a directory, symbolic link, or invalid url."}**

Do you have any idea how I can solve it?

**Comment by robingenz** [comment]
@FrancescoIoppolo `capacitor://localhost/capacitor_file/private/var/mobile/Containers/Data/Application/30DED4BA-4EB9-4F3A-AC39-BB7F7AA46053/tmp/photo-5. jpg` is a web URL and not a native path. You need to provide a native path.

**Example** (not tested):
```ts
import { Camera, CameraResultType } from '@capacitor/camera';

const uploadPicture = async () => {
  const image = await Camera.getPhoto({
    resultType: CameraResultType.Uri
  });
  await FirebaseStorage.uploadFile(
      {
        path: image.path.split("/").slice(-1).pop(),
        uri: image.path,
      },
      (event, error) => {
        console.log({ event, error });
      }
    );
};
```

**Comment by FrancescoIoppolo** [comment]
> @FrancescoIoppolo `capacitor://localhost/capacitor_file/private/var/mobile/Containers/Data/Application/30DED4BA-4EB9-4F3A-AC39-BB7F7AA46053/tmp/photo-5. jpg` is a web URL and not a native path. You need to provide a native path.
> 
> **Example** (not tested):
> 
> ```ts
> import { Camera, CameraResultType } from '@capacitor/camera';
> 
> const uploadPicture = async () => {
>   const image = await Camera.getPhoto({
>     resultType: CameraResultType.Uri
>   });
>   await FirebaseStorage.uploadFile(
>       {
>         path: image.path.split("/").slice(-1).pop(),
>         uri: image.path,
>       },
>       (event, error) => {
>         console.log({ event, error });
>       }
>     );
> };
> ```

yes you are right! I didn't realize I had uri: image.webPath! Thank you 🙌🏻🙌🏻

**Comment by FrancescoIoppolo** [comment]
I have another question. Can I upload an image from a link? In the case of Social login I would like to use the profile image and upload to storage.

**Comment by CatalystMonish** [comment]
> I have another question. Can I upload an image from a link? In the case of Social login I would like to use the profile image and upload to storage.

Do it in background when the user signs up, get the image from the link first then upload it to storage.

**Comment by FrancescoIoppolo** [comment]
> > I have another question. Can I upload an image from a link? In the case of Social login I would like to use the profile image and upload to storage.
> 
> Do it in background when the user signs up, get the image from the link first then upload it to storage.

Correct, but I can't use the upload function for an image url. What approach should I use to convert it to URI?

**Comment by robingenz** [comment]
> > > I have another question. Can I upload an image from a link? In the case of Social login I would like to use the profile image and upload to storage.
> > 
> > 
> > Do it in background when the user signs up, get the image from the link first then upload it to storage.
> 
> Correct, but I can't use the upload function for an image url. What approach should I use to convert it to URI?

For now, you can simply download the image to the device (using `Filesystem.downloadFile(..)`) and upload it to Firestore. Feel free to submit a feature request for passing urls directly.

**Comment by FrancescoIoppolo** [comment]
Everything is working great, great job! thanks

**Pull request merged**
